
/* 

GARANTIZANDO QUE FUNCIONE BYOM SI ESTÁ INSTALADO EN EL USUARIO MLDB

GRANT EXECUTE PROCEDURE ON mldb TO user_ds;
GRANT EXECUTE FUNCTION ON mldb TO user_ds;
GRANT SELECT ON mldb TO user_ds;

GARANTIZANDO QUE FUNCIONE EL STORED PROCEDURE ANALÍTICO SI ESTÁ INSTALADO EN EL USUARIO VAL

GRANT EXECUTE PROCEDURE ON val TO user_ds;
GRANT EXECUTE FUNCTION ON val TO user_ds;
GRANT SELECT ON val TO user_ds;

*/


--DROP TABLE lc250058.credit_train;

CREATE MULTISET TABLE lc250058.credit_train 
    (
    ID INTEGER,
    LIMIT_BAL INTEGER,
    SEX SMALLINT,
    EDUCATION SMALLINT,
    MARRIAGE SMALLINT,
    AGE SMALLINT,
    PAY_1 SMALLINT,
    PAY_2 SMALLINT,
    PAY_3 SMALLINT,
    PAY_4 SMALLINT,
    PAY_5 SMALLINT,
    PAY_6 SMALLINT,
    BILL_AMT1 FLOAT,
    BILL_AMT2 FLOAT,
    BILL_AMT3 FLOAT,
    BILL_AMT4 FLOAT,
    BILL_AMT5 FLOAT,
    BILL_AMT6 FLOAT,
    PAY_AMT1 FLOAT,
    PAY_AMT2 FLOAT,
    PAY_AMT3 FLOAT,
    PAY_AMT4 FLOAT,
    PAY_AMT5 FLOAT,
    PAY_AMT6 FLOAT,
    EDUCATION_1 SMALLINT,
    EDUCATION_2 SMALLINT,
    EDUCATION_3 SMALLINT,
    MARRIAGE_1 SMALLINT,
    MARRIAGE_2 SMALLINT,
    LOG_BILL_AMT1 FLOAT,
    LOG_BILL_AMT2 FLOAT,
    LOG_BILL_AMT3 FLOAT,
    LOG_BILL_AMT4 FLOAT,
    LOG_BILL_AMT5 FLOAT,
    LOG_BILL_AMT6 FLOAT,
    LOG_PAY_AMT1 FLOAT,
    LOG_PAY_AMT2 FLOAT,
    LOG_PAY_AMT3 FLOAT,
    LOG_PAY_AMT4 FLOAT,
    LOG_PAY_AMT5 FLOAT,
    LOG_PAY_AMT6 FLOAT,
    SUM_PAY_TOT SMALLINT,
    STD_PAY_TOT FLOAT,
    SUM_PAY_REC SMALLINT,
    CANT_PAY_MAY0 SMALLINT,
    AVG_LBILL_TOT FLOAT,
    STD_LBILL_TOT FLOAT,
    CV_LBILL_TOT FLOAT,
    SUM_LBILL_REC FLOAT,
    CANT_LBILL_MAY0 SMALLINT,
    AVG_LPAY_TOT FLOAT,
    STD_LPAY_TOT FLOAT,
    CV_LPAY_TOT FLOAT,
    SUM_LPAY_REC FLOAT,
    CANT_LPAY_MAY0 SMALLINT,
    RATE_PAY_BILL1 FLOAT,
    RATE_PAY_BILL2 FLOAT,
    TAR SMALLINT)
    PRIMARY INDEX (ID);

    
select count(1) n from lc250058.credit_train;

